### PR TITLE
New tutorial

### PR DESCRIPTION
**Pull request by nickslick03**
Better late than never 😅. I made a new tutorial modal that highlights each of the sections. Here's some of the top-level highlights:

- I renamed the help modals to "tooltip." I now realize this is probably not the most accurate naming, but this helps differentiate between the two instruction functions.
- Getting the elements with the document object did not go as planned, so I'm getting them through refs and context
- An issue I just thought of that I didn't address is that when the tutorial modal is under the meal plan info section, and the user enters invalid info, the section element gets covered by the modal since the height increases. If you have any ideas for a fix or different way of doing this with that I'm all ears.
- I had to move the "add custom meal" modal to render outside the available meals container to get the z indexing to work properly. It didn't seem to break anything so let me know if that may cause side effects.

### CODE REVIEW

**Review by cdrice26 — COMMENTED** [review]
Okay, so here's what I'm thinking with this one. Firstly, I was originally under the understanding that both this and my tutorials would always be available, and that doesn't appear to be the case here, and I think having this tutorial only available on startup and then relying on my tooltips later on probably doesn't make the most sense. And the more I think about it, I think this is a far better way of doing a tutorial in general given that it's interactive. So what I think we should do here is go back to your earlier idea of having a "more details" link in each tutorial modal that when clicked would expand the modal to include all the information included in my tutorial (minus the screenshots, since interactivity renders them unnecessary). This wouldn't fit well in a modal, however, and so what I'm thinking here is on large screens, we have the content slide over to one side of the screen and have a tutorial expand as a sidebar or card off to the other side (I believe flexbox combined with dynamically setting the margin should make this fairly straightforward). That would solve the issue with the meal plan info as well. That wouldn't work on small screens though, so below the small breakpoint I think instead of flexing horizontally, we flex verticaly and have the turorial occupy the bottom third or so of the screen when it's open. This would also allow us to avoid some prop drilling and consolidate some code, as we could just use a context for active tutorial which would either be null if there isn't one, or the name of a section, that is set by clicking the "help" buttons or by being a new user, that is then used by the App component to conditionally render the tutorial, which could be its own (much higher-level) component. Let me know what you think of this, and if it's something you're interested in, let me know how much of the coding you want to do - I realize this would be pretty substantial and I'm willing to jump in and help if this is the way we want to go, but this was your idea so if you want to do it, it's all yours:). Let me know if you have any other thoughts or ideas as well.

**Comment by nickslick03** [comment]
added discussed changes to new tutorial

**Review by cdrice26 — COMMENTED** [review]
Alright, looks great! I've updated the tutorial so that it flows more smoothly from the less detailed version to the more detailed, and added an action for each step (save for intro and conclusion) and moved the action to be below even the detailed tutorial (otherwise it looks a bit choppy when I open the details). I've also refactored just a bit to fix some TS errors. I also made the 'x' button available on all tutorial steps so the user can exit if they are just trying to pull up help for one section. I'm ready to merge anytime.

**Comment by nickslick03** [comment]
Awesome! Just one thing, in the tutorial component there is an "isStepComplete" memo on line 58, in which you can add validation for each step. Are you fine with users being able to skip past the tutorial steps without completing the actions or do you want to add some validation?

**Comment by cdrice26** [comment]
Thanks for pointing that out, I didn't see that originally. I'd be okay with users being able to skip past steps, I think it makes sense for the meal plan info since that's required to move on anyway, but beyond that I think if the user wants to do it differently (e.g. add directly to a day and skip the meal queue) it could be frustrating to be forced to follow the tutorial. The same issue would occur if the user was just checking the tutorial for reference later on.

**Pull request merged**
