### PR TITLE
Tutorial

### PR DESCRIPTION
**Pull request by cdrice26**
Added the tutorial modals. Implementation is pretty straightforward, I just created a TutorialModal component and a static file to hold the markup for each section. Implements #35.

### CODE REVIEW

**Comment by nickslick03** [comment]
looks good, I added some height and width constraints so it presents nicely on a desktop display. Totally pushable bro.

**Comment by nickslick03** [comment]
Also, the tutorial doesn't pop up for new users, was it intentional to keep the tutorial as helper articles?

**Comment by cdrice26** [comment]
Oops, yeah that was my bad, I forgot about making it appear on first launch and I also should have known better than to create this PR at the same time as the charts one since that had so many extensive modifications...but anyway, it now shows up on first launch. Let me know what you think, I'm good to merge at this point whenever you are.

**Comment by nickslick03** [comment]
Looks good! Just wondering, is there a reason you started on the available meals section instead of the meal info section?

**Comment by cdrice26** [comment]
Oops, yeah no, that wasn't right. It starts on Meal Plan Info now:)

**Pull request merged**
