### PR TITLE
Created favicon

### PR DESCRIPTION
**Pull request by cdrice26**
Added a favicon, and also used it as a logo added to the header. Certainly willing to tweak it some if you have ideas.

### CODE REVIEW

**Comment by nickslick03** [comment]
honestly, I don't think a whole logo is needed for a project like this. I liked the look of a minimalist header, and a calendar or fork emoji (📅 🍴) as the favicon would work nicely. Let me know what you think about this.

**Comment by cdrice26** [comment]
I do see what you mean about the minimalist header, as a logo doesn't really fit into the design aesthetic it currently has, so I'm okay with removing it there. I also don't think a logo that complex works well as a favicon if it's not used in the app anywhere at a larger size, as the user won't be able to even tell what it is most times. That said, I'm a bit less sold on the look of an emoji as the favicon and would like something a little more specific to the app. I'll try to come up with a more clean and minimal icon, maybe just a fork with a list next to it or something.

**Review by cdrice26 — COMMENTED** [review]
Alright I updated the favicon to something simpler, let me know what you think.

**Comment by nickslick03** [comment]
haha this is awesome, it looks like the American flag

**Pull request merged**
