### PR TITLE
Fixed results help button

### PR DESCRIPTION
**Pull request by cdrice26**
Quick fix to get the results help button working.

### CODE REVIEW

**Comment by nickslick03** [comment]
smallest PR ever

**Comment by cdrice26** [comment]
yeah literally...I almost just pushed straight to development and probably could have considering how simple this turned out to be, haha

**Comment by nickslick03** [comment]
results

So I setup the repo on my pc so that could be the problem, but the results popup doesn't appear when I click directly on it but it does appear when I click "next." Is this happening to you?

**Comment by nickslick03** [comment]
my b ... I was looking at the gh page ... 💀

**Pull request merged**
