### PR TITLE
Animations

### PR DESCRIPTION
**Pull request by cdrice26**
Added css animations. Color changes now have a fade effect and the selectors now slide. There is a bit of weirdness as I had to put a manual vertical offset on the highlighter component to get it to display properly on the MealTable, but it works.

### CODE REVIEW

**Comment by nickslick03** [comment]
Animations and transitions look great! I love you idea of the selected day button background moving to the different days. 2 things:
image
1. The z indices seem to be with the modal.
2. It seems you tried to replicate the day selector button bar selection animation with the "all / custom only" option next to the search bar in the available meals. Still, I see both a sliding square and the static background fading in. Was this intentional?

**Comment by nickslick03** [comment]
also the "no meals to display" div isn't centered anymore

**Comment by cdrice26** [comment]
All those issues are fixed. The one with the custom meal toggle was just due to the hover: and active: directives, to smooth it out I completely removed the active one and made hover conditional on not being the selected button.

**Comment by nickslick03** [comment]
image
now the weekday buttons are in front of the results bar 😲

**Comment by cdrice26** [comment]
Should be fixed now.

**Comment by nickslick03** [comment]
I re centered the notification component and put it in the front

**Comment by nickslick03** [comment]
okay so I just fought to the death with git, pls double-check that nothing is broken mainly in the meal table component. my b

**Comment by cdrice26** [comment]
Still working fine for me from what I can tell

**Pull request merged**
