### PR TITLE
Calculations and input

### PR DESCRIPTION
**Pull request by nickslick03**
Big things:
- The input component has changed from it's value prop being a (string | number | boolean) to a generic, (T | null), where T means that the input is valid and null means the input is invalid. This change is also reflected in the persistentState hook, which returns the actual value and not the string representation. This means when using the context values throughout the app, null checking is needed, but is better then the hodge podge checking I was doing previously.
- The inputs now have a invalid message. They currently show by using display: hidden; which can widen the meal info inner container a bit. Using visibility: invisible; fixes this but adds uneven spacing between the inputs. let me know what you think of this.
- The getMealTotal now takes an array of all the meal listings to search from.
You'll probably have to clear your localStorage. Let me know what you think.

### CODE REVIEW

**Comment by nickslick03** [comment]
- I don't have a Mac so I can't replicate the error, so I built the commit I just made to gh-pages and tried it on my iPhone and there is an invalid input message on the starting balance. Maybe try some console logging to see if there's a macOS Safari-specific issue. I'd start around line 93 in Input.tsx to see what `newValue` is. That's weird that it only happens on Safari.
- 👍good catch
- fixed the resultsBar glitch and moved results and resultsBar memos up to App.tsx to avoid redundancy.
- I'm not seeing that issue, so keep an eye out ig

**Comment by cdrice26** [comment]
Okay so I'm actually seeing the error message now in Safari, the only exception being if the starting balance in localStorage is null when the page is loaded and then it won't show up until you type a number into it and then mess it up because the value just stays null. I just discovered that the weird price issue is just because I had the dining dollars discount turned on and it automatically adjusts the prices. If you want to take a look at the issue of it not seeing an initial null, feel free, otherwise I think it's good to merge.

**Comment by cdrice26** [comment]
Although the issue of the error message on the starting balance not showing initially may be more of a feature than a bug...I would be kind of annoyed if I started up an app and it was already giving me error messages, haha. But it is misleading to be able to type nonsense into it and have it still be null without sending an error because no state has been updated. Is this specific to Safari or are you able to replicate this particular behavior?

**Comment by cdrice26** [comment]
Oh yes I forgot about the onInput event, I think that's actually considered the better event to use for capturing input from a <input> so we're good there. Yes, it's still a behemoth component, but it works and so I think we're good at this point. I'm going to merge.

**Pull request merged**
