### PR TITLE
Result charts

### PR DESCRIPTION
**Pull request by nickslick03**
Created two charts: a stacked bar chart displaying the amount spent per week stacked by location, and a pie chart with the amount paid per week by location. It might make more sense to show the totals spent instead of weekly but that might be a separate PR to write extra helper functions since the calculator is only set up to return one meal total.

### CODE REVIEW

**Comment by cdrice26** [comment]
Okay, I've looked over it and it's definitely nice to have these great charts in the results section! I did make several changes:
- Fixed some TypeScript errors.
- Improved documentation.
- Applied border/background styling to both charts.
- Created a responsive layout where the charts are displayed side-by-side on desktop and one above the other on mobile.
- Modified the tooltips on the charts to display the value formatted as currency and for the pie chart, also the percentage of the total week cost.
- Refactored the code to use our existing formatCurrency function rather than rewriting it here.
- Fixed bug where custom meals would not be included in the charts.

**Comment by nickslick03** [comment]
Wow, everything looks great! I've made it so that the charts now account for the student plan meal price. Unfortunately, when testing out the app I did notice some weird behavior from entering the start date and end date (put ` console.log({ startDate, endDate });` into App.tsx and you'll see what I'm talking about), which only happens in this PR and not in the development branch. Before doing a deep dive I'm working if there's any code you've written in this PR that could be causing this?

**Comment by cdrice26** [comment]
Huh, that's really weird, I can't think of anything, and I'm fairly certain I didn't add anything that sets the date (I did a quick search for startDate across the whole project and couldn't seem to find anything problematic)...but you're right, for some reason the start date seems to be setting to two days after the day you selected. I can keep looking over this as well, and hopefully between the two of us we'll find something?

**Comment by cdrice26** [comment]
I think I fixed it! The problem was my getAllDatesBetween function, it was calling ```setDate()``` on the ```startDate``` which was passed in as a parameter, and ```Date``` is a reference type. I fixed it by having it create a new ```Date``` when it calls itself instead of mutating ```startDate```.

**Pull request merged**
