### PR TITLE
Multiple weeks off

### PR DESCRIPTION
**Pull request by nickslick03**
Changed the isBreak checkbox to weeksOff number when calculating the total cost. I noticed a couple of weeks I want to ask about:

- at around line 242 of results.tsx you put another dot leader row titled "Date when money runs out," and you had a ternary "(assuming your break is before this)." But now that the the dayWhenRunOut function accounts for the weekOff, or now weeksOff, this clause is obsolete, right?
- at line 72 in calculationEngine.ts, in the function calculateDateWhenRunOut, you put a .slice(7) call on the dates array when isBreak is true. Reading the documentation says that the slice function takes an index, not the number of elements to be removed, so should it be 6 instead?

### CODE REVIEW

**Comment by cdrice26** [comment]
In short, the answer to both of those questions would be "no". The dayWhenRunOut function has always accounted for it, and the purpose of including that phrase when week off was on was to alert the user that the week was being subtracted and that if the break was actually after the date when you run out, your meal plan would last one week less. In other words, the dayWhenRunOut function assumes the break is the first week, and the user should be aware of that. Regarding the slice function, I need to remove the first seven items from the list, and the argument to slice is the first index to keep. So I need to exclude indices 0 through 6 (which amounts to 7 days) and keep indices 7 and on, so I pass in 7.

**Comment by cdrice26** [comment]
So both need to be updated but not removed:)

**Comment by nickslick03** [comment]
I see. ready to push when you are.

**Comment by cdrice26** [comment]
Ok cool looks great!

**Pull request merged**
